[versions]
compose = "2025.11.00"

[libraries]
bom = { module = "androidx.compose:compose-bom", version.ref = "compose" }
animation = { module = "androidx.compose.animation:animation" }
foundation = { module = "androidx.compose.foundation:foundation" }
material3 = { module = "androidx.compose.material3:material3" }
material-motion = { module = "io.github.fornewid:material-motion-compose-core", version = "2.0.1" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
icons = { module = "androidx.compose.material:material-icons-extended" }
webview = { module = "io.github.kevinnzou:compose-webview", version = "0.33.6" }

activity = { module = "androidx.activity:activity-compose", version = "1.11.0" }
material3-core = { module = "androidx.compose.material3:material3" }
material-icons = { module = "androidx.compose.material:material-icons-extended" }
animation-graphics = { module = "androidx.compose.animation:animation-graphics" }
ui-util = { module = "androidx.compose.ui:ui-util" }
runtime = { module = "androidx.compose.runtime:runtime" }
glance = { module = "androidx.glance:glance-appwidget", version = "1.1.1" }

[bundles]
compose = [ "animation", "foundation", "material3", "material-motion", "ui-tooling-preview", "icons" ]
